### ISSUE TITLE
mixed information and clarification 

### ISSUE THREAD

**Issue by WhatTheFunnn** [learn-co-curriculum/phase-1-scope-readme#1]
### Canvas Link

https://learning.flatironschool.com/courses/4968/pages/setting-up-wsl2?module_item_id=321579

### Concern

Variables declared in function scope vs block scope. Typically you would create a block inside of a function. If this is the case, the article states that a variable declared within block scope would be available globally if declared with const, or let. But at the bottom the article says that variables declared within a function would not be available globally. Looking for clarification, cause from experience in past labs I would have to declare a variable outside of function scope in order for other functions to read them unless I called the function into that current function.

**Comment by lizbur10** [comment]
Hi @WhatTheFunnn! You are correct that variables declared inside a function block (or any block, for that matter) are not available globally, as long as they're declared with `const` or `let`. 

I'm not seeing where it says otherwise - can you point me to a line number?

Thanks as always for contributing! 💙

**Comment by lizbur10** [comment]
Hi again @WhatTheFunnn ! I'm going to go ahead and close this issue. If you believe there is still a problem with the lesson feel free to reopen it 💙
