### ISSUE TITLE
Global Gotcha Section

### ISSUE THREAD

**Issue by timtran007** [learn-co-curriculum/phase-1-scope-readme#2]
### Canvas Link

https://learning.flatironschool.com/courses/5649/pages/introduction-to-scope?module_item_id=478980

### Concern

During my code-along with this portion 

I went to repl.it 

And tried on a index.js and index.html file to run the code

function bankAccount() {
  secretPassword = "il0v3pupp135";

  return "bankAccount() function invoked!";
}

secretPassword;

And I get the ReferenceError that secretPassword is undefined

### Additional Context

Did the Global Gotcha section changed?

**Comment by jlboba** [comment]
Hello! Thanks for raising this issue. Based on your description however, it looks like you forgot one step in your code. Between defining the `bankAccount` function and referencing `secretPassword` variable, the function has to be invoked for the variable to be defined globally. Try it again with that invocation in between and it should work! 

If you need more help with this, please feel free to either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success Team

Otherwise, I will now be closing this issue. Hope that helps!
